# child values
vgpu:
  # Default values for 4pd-vgpu.
  nameOverride: ""
  fullnameOverride: ""
  imagePullSecrets: []
  version: "v2.3.7"
  #Nvidia GPU Parameters
  resourceName: "nvidia.com/vgpu"
  resourceMem: "nvidia.com/gpumem"
  resourceMemPercentage: "nvidia.com/gpumem-percentage"
  resourceCores: "nvidia.com/gpucores"
  resourcePriority: "nvidia.com/priority"
  #MLU Parameters
  mluResourceName: "cambricon.com/mlunum"
  mluResourceMem: "cambricon.com/mlumem"
  #Hygon DCU Parameters
  dcuResourceName: "hygon.com/dcunum"
  dcuResourceMem: "hygon.com/dcumem"
  dcuResourceCores: "hygon.com/dcucores"
  schedulerName: "4pd-scheduler"
  podSecurityPolicy:
    enabled: false
  global:
    labels: {}
    annotations: {}
  scheduler:
    defaultMem: 0
    defaultCores: 0
    kubeScheduler:
      imageTag: "v1.24.0"
      registry: k8s-gcr.m.daocloud.io
      repository: kubernetes/kube-scheduler
      imagePullPolicy: IfNotPresent
      extraNewArgs:
        - --config=/config/config.yaml
        - -v=4
      extraArgs:
        - --policy-config-file=/config/config.json
        - --leader-elect=false
        - -v=4
    extender:
      registry: docker.m.daocloud.io
      repository: 4pdosc/k8s-vdevice
      #image: "m7-ieg-pico-test01:5000/k8s-vgpu-test:latest"
      imagePullPolicy: IfNotPresent
      extraArgs:
        - --debug
        - -v=4
    podAnnotations: {}
    #nodeSelector: 
    #  gpu: "on"
    tolerations: []
    #serviceAccountName: "4pd-vgpu-scheduler-sa"
    customWebhook:
      enabled: false
      # must be an endpoint using https.
      # should generate host certs here
      host: 127.0.0.1 # hostname or ip, can be your node'IP if you want to use https://<nodeIP>:<schedulerPort>/<path>
      port: 31998
      path: /webhook
    patch:
      registry: docker.m.daocloud.io
      repository: jettech/kube-webhook-certgen
      tag: v1.5.2
      newRepository: liangjw/kube-webhook-certgen
      newTag: v1.1.1
      imagePullPolicy: IfNotPresent
      priorityClassName: ""
      podAnnotations: {}
      nodeSelector: {}
      tolerations: []
      runAsUser: 2000
    service:
      httpPort: 443
      schedulerPort: 31998
      monitorPort: 31993
      labels: {}
      annotations: {}
    nodeSelector:
      nvidia.com/gpu.deploy.driver: "true"
    serviceMonitor:
      enable: false
  devicePlugin:
    registry: docker.m.daocloud.io
    repository: 4pdosc/k8s-vdevice
    monitorimage: "4pdosc/k8s-vdevice"
    monitorctrPath: /usr/local/vgpu/containers
    imagePullPolicy: IfNotPresent
    deviceSplitCount: 10
    deviceMemoryScaling: 1
    deviceCoreScaling: 1
    runtimeClassName: ""
    migStrategy: "none"
    disablecorelimit: "false"
    extraArgs:
      - -v=false
    hygonimage: "4pdosc/vdcu-device-plugin:v1.0"
    hygondriver: "/root/dcu-driver/dtk-22.10.1-vdcu"
    service:
      httpPort: 31992
    pluginPath: /var/lib/kubelet/device-plugins
    libPath: /usr/local/vgpu
    podAnnotations: {}
    nvidianodeSelector:
      nvidia.com/gpu.deploy.driver: "true"
      nvidia.com/vgpu.deploy.device-plugin: "true"
    mlunodeSelector:
      mlu: "on"
    hygonnodeSelector:
      dcu: "on"
    tolerations: []
    hygonImageRepository: 4pdosc/vdcu-device-plugin
    hygonImageTag: v1.0
  resources:
    limits:
      cpu: 500m
      memory: 720Mi
    requests:
      cpu: 100m
      memory: 128Mi
